name: Deploy CI

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy to Cloudflare Workers
        steps:
            - uses: actions/checkout@v4

            - name: Install Node.js
              run: sudo snap install node --channel=24/stable --classic

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install deps
              run: pnpm install

            - name: Deploy with wrangler
              run: pnpm run deploy
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
